name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, metadata
          plugin_lines: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_repositories: 100
          config_timezone: America/Sao_Paulo
