name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # Executa todo dia à meia-noite
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_languages: yes
          config_timezone: America/Sao_Paulo
          template: minimal
